[package]
name = "test_latest"
version = "0.1.0"
authors = ["pingzing <mcalistern@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8.2"
lazy_static = "1.0"